import mongoose from 'mongoose'
import CentroCosto from '../models/CentroCosto.js'

const data = [
  // Tractores
  { grupo: 'Tractores', cc: '101',      marca: 'Fiat 400' },
  { grupo: 'Tractores', cc: '102',      marca: 'CHERY RC 1104 A 115HP' },
  { grupo: 'Tractores', cc: '103',      marca: 'CHERY RC 1104 A 115HP' },
  { grupo: 'Tractores', cc: '104',      marca: 'Deutz 460 c/techo' },
  { grupo: 'Tractores', cc: '110',      marca: 'FHAR 65' },
  { grupo: 'Tractores', cc: '111',      marca: 'Massey 251' },
  { grupo: 'Tractores', cc: '150',      marca: 'VALTRA BF 75' },
  { grupo: 'Tractores', cc: '151',      marca: 'VALTRA BF 75' },
  { grupo: 'Tractores', cc: '152',      marca: 'Valtra 75' },
  { grupo: 'Tractores', cc: '153',      marca: 'Valtra 75' },
  { grupo: 'Tractores', cc: '154',      marca: 'Valtra 75' },
  { grupo: 'Tractores', cc: '155',      marca: 'VALTRA BM110' },
  { grupo: 'Tractores', cc: '156',      marca: 'Valtra 110' },
  { grupo: 'Tractores', cc: '157',      marca: 'Case Farmal 75A' },
  { grupo: 'Tractores', cc: '158',      marca: 'John Deere 5082E' },
  { grupo: 'Tractores', cc: '159',      marca: 'JOHN DEERE 5065E TS' },
  { grupo: 'Tractores', cc: '160',      marca: 'JOHN DEERE 5065E TS' },
  { grupo: 'Tractores', cc: '161',      marca: 'Jhon Deere 5065E' },
  { grupo: 'Tractores', cc: '163',      marca: 'Case 55' },
  { grupo: 'Tractores', cc: '164',      marca: 'JHON DEERE 5065E TD' },
  { grupo: 'Tractores', cc: '165',      marca: 'JHON DEERE 5065E TS' },
  { grupo: 'Tractores', cc: '166',      marca: 'Massey 2625' },
  { grupo: 'Tractores', cc: '168',      marca: 'JOHN DEERE 5410' },
  { grupo: 'Tractores', cc: '171',      marca: 'JOHN DEERE 5410' },
  { grupo: 'Tractores', cc: '174',      marca: 'JOHN DEERE 5310' },
  { grupo: 'Tractores', cc: '179',      marca: 'JOHN DEERE 5310' },
  { grupo: 'Tractores', cc: '183',      marca: 'Massey Ferguson 2625 dt' },
  { grupo: 'Tractores', cc: '184',      marca: 'Apache dt 60' },
  { grupo: 'Tractores', cc: '185',      marca: 'Apache dt 75' },
  { grupo: 'Tractores', cc: '186',      marca: 'Massey 4275' },
  { grupo: 'Tractores', cc: '187',      marca: 'Caseii 75 (02)' },
  { grupo: 'Tractores', cc: '188',      marca: 'Caseii 75' },
  { grupo: 'Tractores', cc: '189',      marca: 'APACHE RX60 DT' },
  { grupo: 'Tractores', cc: '190',      marca: 'DEUTZ (EL PUCARA)' },
  { grupo: 'Tractores', cc: '191',      marca: 'JOHN DEERE 5065' },
  { grupo: 'Tractores', cc: '192',      marca: 'JOHN DEERE 5065' },
  { grupo: 'Tractores', cc: '193',      marca: 'Case 75(03)' },
  { grupo: 'Tractores', cc: '194',      marca: 'CHERY RC 1004 A (105HP)' },
  { grupo: 'Tractores', cc: '195',      marca: 'CHERY RC 1004 A (105HP)' },
  { grupo: 'Tractores', cc: '196',      marca: 'CHERY RD 704-F (75HP)' },
  { grupo: 'Tractores', cc: '197',      marca: 'CHERY RD 704-F (75HP)' },
  { grupo: 'Tractores', cc: '198',      marca: 'CHERY RK 504 A (58HP)' },
  { grupo: 'Tractores', cc: '199/155',  marca: 'CHERY RK 504 A (58HP)' },
  { grupo: 'Tractores', cc: '200/156',  marca: 'CHERY RK 704 A (70HP)' },
  // Colectivos
  { grupo: 'Colectivos', cc: '250', marca: 'EQA 367' },
  { grupo: 'Colectivos', cc: '252', marca: 'EJO008' },
  { grupo: 'Colectivos', cc: '253', marca: 'EKB 410' },
  { grupo: 'Colectivos', cc: '254', marca: 'EQB 127' },
  { grupo: 'Colectivos', cc: '256', marca: 'EQB 118' },
  { grupo: 'Colectivos', cc: '257', marca: 'EPM 608' },
  { grupo: 'Colectivos', cc: '258', marca: 'EOO 472' },
  { grupo: 'Colectivos', cc: '259', marca: 'EOO 471' },
  { grupo: 'Colectivos', cc: '260', marca: 'EIY 007' },
  { grupo: 'Colectivos', cc: '261', marca: 'FNM 075' },
  { grupo: 'Colectivos', cc: '262', marca: 'EVG 847' },
  { grupo: 'Colectivos', cc: '263', marca: 'FFY 939' },
  { grupo: 'Colectivos', cc: '264', marca: 'EIW 252' },
  { grupo: 'Colectivos', cc: '266', marca: 'FBN 948' },
  { grupo: 'Colectivos', cc: '267', marca: 'FHD 974' },
  { grupo: 'Colectivos', cc: '268', marca: 'EWE 315' },
  { grupo: 'Colectivos', cc: '270', marca: 'HMZ 834' },
  { grupo: 'Colectivos', cc: '271', marca: 'HLJ 889' },
  { grupo: 'Colectivos', cc: '272', marca: 'HFF 720' },
  { grupo: 'Colectivos', cc: '273', marca: 'HIG 882' },
  { grupo: 'Colectivos', cc: '275', marca: 'JCU415' },
  { grupo: 'Colectivos', cc: '276', marca: 'JCU419' },
  { grupo: 'Colectivos', cc: '277', marca: 'IWB242' },
  { grupo: 'Colectivos', cc: '278', marca: 'IYD469' },
  { grupo: 'Colectivos', cc: '279', marca: 'IUG113' },
  { grupo: 'Colectivos', cc: '280', marca: 'ISM637' },
  { grupo: 'Colectivos', cc: '281', marca: 'ITS 353' },
  { grupo: 'Colectivos', cc: '282', marca: 'FTV300' },
  { grupo: 'Colectivos', cc: '283', marca: 'FWN' },
  // Pulverizadora
  { grupo: 'Pulverizadora', cc: '301', marca: 'FMC 1' },
  { grupo: 'Pulverizadora', cc: '302', marca: 'FAMECO' },
  { grupo: 'Pulverizadora', cc: '303', marca: 'FMC 3' },
  { grupo: 'Pulverizadora', cc: '304', marca: 'El PUMA' },
  { grupo: 'Pulverizadora', cc: '305', marca: 'El PUMA' },
  { grupo: 'Pulverizadora', cc: '306', marca: 'Martiniani' },
  { grupo: 'Pulverizadora', cc: '307', marca: 'Pulv. c/ Lanza x 1500Lts' },
  { grupo: 'Pulverizadora', cc: '308', marca: 'FAMECO' },
  { grupo: 'Pulverizadora', cc: '350', marca: 'Jacto Arbus 4000' },
  { grupo: 'Pulverizadora', cc: '351', marca: 'Jacto Arbus 4000' },
  { grupo: 'Pulverizadora', cc: '352', marca: 'Metalfor Selec 4000' },
  // Chancho
  { grupo: 'Chancho', cc: '501', marca: 'Chancho' },
  { grupo: 'Chancho', cc: '502', marca: 'Chancho' },
  { grupo: 'Chancho', cc: '503', marca: 'Chancho' },
  { grupo: 'Chancho', cc: '504', marca: 'Chancho' },
  { grupo: 'Chancho', cc: '505', marca: 'Chancho' },
  { grupo: 'Chancho', cc: '550', marca: 'Cisterna Bara Herb' },
  { grupo: 'Chancho', cc: '551', marca: 'Cisterna Bara Herb' },
  { grupo: 'Chancho', cc: '552', marca: 'S/N' },
  { grupo: 'Chancho', cc: '553', marca: 'S/N' },
  { grupo: 'Chancho', cc: '554', marca: 'Metalfor 2000 c/barra lateral' },
  { grupo: 'Chancho', cc: '555', marca: 'Metalfor 2000 c/barra lateral' },
  // Camioneta
  { grupo: 'Camioneta', cc: 'AI245IG', marca: 'Amarok' },
  { grupo: 'Camioneta', cc: 'AG224AR', marca: 'Amarok blanca c/d' },
  { grupo: 'Camioneta', cc: 'AA225RH', marca: 'Amarok blanca c/s' },
  { grupo: 'Camioneta', cc: 'AA225RN', marca: 'Amarok gris c/d' },
  { grupo: 'Camioneta', cc: 'AB926IN', marca: 'Chevrolet S-10' },
  { grupo: 'Camioneta', cc: 'OQQ126',  marca: 'Fiat Strada blanca' },
  { grupo: 'Camioneta', cc: 'AE233IV', marca: 'Ford Ranger blanca c/d' },
  { grupo: 'Camioneta', cc: 'HWW034',  marca: 'Hilux azul' },
  { grupo: 'Camioneta', cc: 'NMJ427',  marca: 'Hilux blanca' },
  { grupo: 'Camioneta', cc: 'HPU482',  marca: 'Hilux gris' },
  { grupo: 'Camioneta', cc: 'AE822BQ', marca: 'Renault Alaskan blanca' },
  { grupo: 'Camioneta', cc: 'MTS604',  marca: 'Saveiro' },
  { grupo: 'Camioneta', cc: 'AH408ZK', marca: 'Saveiro' },
  { grupo: 'Camioneta', cc: 'AH332WY', marca: 'Saveiro' },
  { grupo: 'Camioneta', cc: 'AI212NV', marca: 'Saveiro' },
  { grupo: 'Camioneta', cc: 'AI245HB', marca: 'Saveiro' },
  // Nodriza
  { grupo: 'Nodriza', cc: '701', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '702', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '703', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '704', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '705', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '706', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '707', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '708', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '709', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '710', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '711', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '712', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '713', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '714', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '715', marca: 'NODRIZA' },
  { grupo: 'Nodriza', cc: '716', marca: 'NODRIZA' },
  // Herbicida
  { grupo: 'Herbicida', cc: '1200', marca: '' },
  { grupo: 'Herbicida', cc: '1201', marca: '' },
  { grupo: 'Herbicida', cc: '1202', marca: '' },
  { grupo: 'Herbicida', cc: '1203', marca: '' },
  { grupo: 'Herbicida', cc: '1204', marca: '' },
  { grupo: 'Herbicida', cc: '1205', marca: '' },
  { grupo: 'Herbicida', cc: '1206', marca: '' },
  { grupo: 'Herbicida', cc: '1207', marca: '' },
  { grupo: 'Herbicida', cc: '1208', marca: '' },
  { grupo: 'Herbicida', cc: '1209', marca: '' },
  { grupo: 'Herbicida', cc: '1210', marca: '' },
  { grupo: 'Herbicida', cc: '1211', marca: '' },
  { grupo: 'Herbicida', cc: '1212', marca: '' },
  { grupo: 'Herbicida', cc: '1213', marca: '' },
  { grupo: 'Herbicida', cc: '1214', marca: '' },
  { grupo: 'Herbicida', cc: '1215', marca: '' },
  // Desmalezadora
  { grupo: 'Desmalezadora', cc: '1300', marca: 'S/N' },
  { grupo: 'Desmalezadora', cc: '1301', marca: 'S/N' },
  { grupo: 'Desmalezadora', cc: '1302', marca: 'S/N' },
  { grupo: 'Desmalezadora', cc: '1303', marca: '' },
  { grupo: 'Desmalezadora', cc: '1304', marca: '' },
  { grupo: 'Desmalezadora', cc: '1305', marca: '' },
  { grupo: 'Desmalezadora', cc: '1306', marca: '' },
  { grupo: 'Desmalezadora', cc: '1307', marca: '' },
  { grupo: 'Desmalezadora', cc: '1308', marca: '' },
  { grupo: 'Desmalezadora', cc: '1309', marca: '' },
  { grupo: 'Desmalezadora', cc: '1310', marca: '' },
  { grupo: 'Desmalezadora', cc: '1311', marca: '' },
  { grupo: 'Desmalezadora', cc: '1312', marca: '' },
  { grupo: 'Desmalezadora', cc: '1313', marca: '' },
  { grupo: 'Desmalezadora', cc: '1314', marca: '' },
  { grupo: 'Desmalezadora', cc: '1315', marca: '' },
  { grupo: 'Desmalezadora', cc: '1316', marca: '' },
  { grupo: 'Desmalezadora', cc: '1317', marca: '' },
  { grupo: 'Desmalezadora', cc: '1318', marca: '' },
  { grupo: 'Desmalezadora', cc: '1319', marca: 'Tractorcito Desmalesadora' },
  { grupo: 'Desmalezadora', cc: '1320', marca: 'Tractorcito Desmalesadora' },
  // Abonadora
  { grupo: 'Abonadora', cc: '1400', marca: 'SYRA 4000' },
  // Manitou
  { grupo: 'Manitou', cc: '1100', marca: 'Manitou' },
  { grupo: 'Manitou', cc: '1101', marca: 'Manitou' },
  { grupo: 'Manitou', cc: '1102', marca: 'Manitou' },
  { grupo: 'Manitou', cc: '1103', marca: 'Manitou' },
  { grupo: 'Manitou', cc: '1104', marca: 'Manitou' },
]

async function seed() {
  await mongoose.connect(process.env.MONGODB)
  console.log('Conectado a MongoDB')

  await CentroCosto.deleteMany({})
  console.log('Colección limpiada')

  const result = await CentroCosto.insertMany(data)
  console.log(`Insertados ${result.length} centros de costo`)

  await mongoose.disconnect()
  console.log('Listo.')
}

seed().catch(err => { console.error(err); process.exit(1) })
